// ============================================================
// Ronde 40-B — Daftar negara (UN members + wilayah umum)
// Sumber kode: ISO 3166-1 alpha-2 (iso2), E.164 (dial), ISO 4217 (currency).
// Diurut alfabetis by `name` (nama Inggris/internasional) — JANGAN acak ulang.
// ============================================================

export interface Country {
  /** Nama Inggris/internasional yang tampil di UI (mis. "Indonesia", "United States"). */
  name: string;
  /** ISO 3166-1 alpha-2 (mis. "ID"). */
  iso2: string;
  /** Kode telepon internasional dengan prefix "+" (mis. "+62"). */
  dial: string;
  /** Mata uang ISO 4217 (mis. "IDR"). */
  currency: string;
}

export const COUNTRIES: Country[] = [
  { name: "Afghanistan", iso2: "AF", dial: "+93", currency: "AFN" },
  { name: "Albania", iso2: "AL", dial: "+355", currency: "ALL" },
  { name: "Algeria", iso2: "DZ", dial: "+213", currency: "DZD" },
  { name: "American Samoa", iso2: "AS", dial: "+1684", currency: "USD" },
  { name: "Andorra", iso2: "AD", dial: "+376", currency: "EUR" },
  { name: "Angola", iso2: "AO", dial: "+244", currency: "AOA" },
  { name: "Anguilla", iso2: "AI", dial: "+1264", currency: "XCD" },
  { name: "Antigua and Barbuda", iso2: "AG", dial: "+1268", currency: "XCD" },
  { name: "Argentina", iso2: "AR", dial: "+54", currency: "ARS" },
  { name: "Armenia", iso2: "AM", dial: "+374", currency: "AMD" },
  { name: "Aruba", iso2: "AW", dial: "+297", currency: "AWG" },
  { name: "Australia", iso2: "AU", dial: "+61", currency: "AUD" },
  { name: "Austria", iso2: "AT", dial: "+43", currency: "EUR" },
  { name: "Azerbaijan", iso2: "AZ", dial: "+994", currency: "AZN" },
  { name: "Bahamas", iso2: "BS", dial: "+1242", currency: "BSD" },
  { name: "Bahrain", iso2: "BH", dial: "+973", currency: "BHD" },
  { name: "Bangladesh", iso2: "BD", dial: "+880", currency: "BDT" },
  { name: "Barbados", iso2: "BB", dial: "+1246", currency: "BBD" },
  { name: "Belarus", iso2: "BY", dial: "+375", currency: "BYN" },
  { name: "Belgium", iso2: "BE", dial: "+32", currency: "EUR" },
  { name: "Belize", iso2: "BZ", dial: "+501", currency: "BZD" },
  { name: "Benin", iso2: "BJ", dial: "+229", currency: "XOF" },
  { name: "Bermuda", iso2: "BM", dial: "+1441", currency: "BMD" },
  { name: "Bhutan", iso2: "BT", dial: "+975", currency: "BTN" },
  { name: "Bolivia", iso2: "BO", dial: "+591", currency: "BOB" },
  { name: "Bosnia and Herzegovina", iso2: "BA", dial: "+387", currency: "BAM" },
  { name: "Botswana", iso2: "BW", dial: "+267", currency: "BWP" },
  { name: "Brazil", iso2: "BR", dial: "+55", currency: "BRL" },
  { name: "British Virgin Islands", iso2: "VG", dial: "+1284", currency: "USD" },
  { name: "Brunei", iso2: "BN", dial: "+673", currency: "BND" },
  { name: "Bulgaria", iso2: "BG", dial: "+359", currency: "BGN" },
  { name: "Burkina Faso", iso2: "BF", dial: "+226", currency: "XOF" },
  { name: "Burundi", iso2: "BI", dial: "+257", currency: "BIF" },
  { name: "Cabo Verde", iso2: "CV", dial: "+238", currency: "CVE" },
  { name: "Cambodia", iso2: "KH", dial: "+855", currency: "KHR" },
  { name: "Cameroon", iso2: "CM", dial: "+237", currency: "XAF" },
  { name: "Canada", iso2: "CA", dial: "+1", currency: "CAD" },
  { name: "Cayman Islands", iso2: "KY", dial: "+1345", currency: "KYD" },
  { name: "Central African Republic", iso2: "CF", dial: "+236", currency: "XAF" },
  { name: "Chad", iso2: "TD", dial: "+235", currency: "XAF" },
  { name: "Chile", iso2: "CL", dial: "+56", currency: "CLP" },
  { name: "China", iso2: "CN", dial: "+86", currency: "CNY" },
  { name: "Colombia", iso2: "CO", dial: "+57", currency: "COP" },
  { name: "Comoros", iso2: "KM", dial: "+269", currency: "KMF" },
  { name: "Congo (Brazzaville)", iso2: "CG", dial: "+242", currency: "XAF" },
  { name: "Congo (Kinshasa)", iso2: "CD", dial: "+243", currency: "CDF" },
  { name: "Cook Islands", iso2: "CK", dial: "+682", currency: "NZD" },
  { name: "Costa Rica", iso2: "CR", dial: "+506", currency: "CRC" },
  { name: "Côte d'Ivoire", iso2: "CI", dial: "+225", currency: "XOF" },
  { name: "Croatia", iso2: "HR", dial: "+385", currency: "EUR" },
  { name: "Cuba", iso2: "CU", dial: "+53", currency: "CUP" },
  { name: "Curaçao", iso2: "CW", dial: "+599", currency: "ANG" },
  { name: "Cyprus", iso2: "CY", dial: "+357", currency: "EUR" },
  { name: "Czechia", iso2: "CZ", dial: "+420", currency: "CZK" },
  { name: "Denmark", iso2: "DK", dial: "+45", currency: "DKK" },
  { name: "Djibouti", iso2: "DJ", dial: "+253", currency: "DJF" },
  { name: "Dominica", iso2: "DM", dial: "+1767", currency: "XCD" },
  { name: "Dominican Republic", iso2: "DO", dial: "+1809", currency: "DOP" },
  { name: "Ecuador", iso2: "EC", dial: "+593", currency: "USD" },
  { name: "Egypt", iso2: "EG", dial: "+20", currency: "EGP" },
  { name: "El Salvador", iso2: "SV", dial: "+503", currency: "USD" },
  { name: "Equatorial Guinea", iso2: "GQ", dial: "+240", currency: "XAF" },
  { name: "Eritrea", iso2: "ER", dial: "+291", currency: "ERN" },
  { name: "Estonia", iso2: "EE", dial: "+372", currency: "EUR" },
  { name: "Eswatini", iso2: "SZ", dial: "+268", currency: "SZL" },
  { name: "Ethiopia", iso2: "ET", dial: "+251", currency: "ETB" },
  { name: "Falkland Islands", iso2: "FK", dial: "+500", currency: "FKP" },
  { name: "Faroe Islands", iso2: "FO", dial: "+298", currency: "DKK" },
  { name: "Fiji", iso2: "FJ", dial: "+679", currency: "FJD" },
  { name: "Finland", iso2: "FI", dial: "+358", currency: "EUR" },
  { name: "France", iso2: "FR", dial: "+33", currency: "EUR" },
  { name: "French Polynesia", iso2: "PF", dial: "+689", currency: "XPF" },
  { name: "Gabon", iso2: "GA", dial: "+241", currency: "XAF" },
  { name: "Gambia", iso2: "GM", dial: "+220", currency: "GMD" },
  { name: "Georgia", iso2: "GE", dial: "+995", currency: "GEL" },
  { name: "Germany", iso2: "DE", dial: "+49", currency: "EUR" },
  { name: "Ghana", iso2: "GH", dial: "+233", currency: "GHS" },
  { name: "Gibraltar", iso2: "GI", dial: "+350", currency: "GIP" },
  { name: "Greece", iso2: "GR", dial: "+30", currency: "EUR" },
  { name: "Greenland", iso2: "GL", dial: "+299", currency: "DKK" },
  { name: "Grenada", iso2: "GD", dial: "+1473", currency: "XCD" },
  { name: "Guam", iso2: "GU", dial: "+1671", currency: "USD" },
  { name: "Guatemala", iso2: "GT", dial: "+502", currency: "GTQ" },
  { name: "Guernsey", iso2: "GG", dial: "+44", currency: "GBP" },
  { name: "Guinea", iso2: "GN", dial: "+224", currency: "GNF" },
  { name: "Guinea-Bissau", iso2: "GW", dial: "+245", currency: "XOF" },
  { name: "Guyana", iso2: "GY", dial: "+592", currency: "GYD" },
  { name: "Haiti", iso2: "HT", dial: "+509", currency: "HTG" },
  { name: "Honduras", iso2: "HN", dial: "+504", currency: "HNL" },
  { name: "Hong Kong", iso2: "HK", dial: "+852", currency: "HKD" },
  { name: "Hungary", iso2: "HU", dial: "+36", currency: "HUF" },
  { name: "Iceland", iso2: "IS", dial: "+354", currency: "ISK" },
  { name: "India", iso2: "IN", dial: "+91", currency: "INR" },
  { name: "Indonesia", iso2: "ID", dial: "+62", currency: "IDR" },
  { name: "Iran", iso2: "IR", dial: "+98", currency: "IRR" },
  { name: "Iraq", iso2: "IQ", dial: "+964", currency: "IQD" },
  { name: "Ireland", iso2: "IE", dial: "+353", currency: "EUR" },
  { name: "Isle of Man", iso2: "IM", dial: "+44", currency: "GBP" },
  { name: "Israel", iso2: "IL", dial: "+972", currency: "ILS" },
  { name: "Italy", iso2: "IT", dial: "+39", currency: "EUR" },
  { name: "Jamaica", iso2: "JM", dial: "+1876", currency: "JMD" },
  { name: "Japan", iso2: "JP", dial: "+81", currency: "JPY" },
  { name: "Jersey", iso2: "JE", dial: "+44", currency: "GBP" },
  { name: "Jordan", iso2: "JO", dial: "+962", currency: "JOD" },
  { name: "Kazakhstan", iso2: "KZ", dial: "+7", currency: "KZT" },
  { name: "Kenya", iso2: "KE", dial: "+254", currency: "KES" },
  { name: "Kiribati", iso2: "KI", dial: "+686", currency: "AUD" },
  { name: "Kosovo", iso2: "XK", dial: "+383", currency: "EUR" },
  { name: "Kuwait", iso2: "KW", dial: "+965", currency: "KWD" },
  { name: "Kyrgyzstan", iso2: "KG", dial: "+996", currency: "KGS" },
  { name: "Laos", iso2: "LA", dial: "+856", currency: "LAK" },
  { name: "Latvia", iso2: "LV", dial: "+371", currency: "EUR" },
  { name: "Lebanon", iso2: "LB", dial: "+961", currency: "LBP" },
  { name: "Lesotho", iso2: "LS", dial: "+266", currency: "LSL" },
  { name: "Liberia", iso2: "LR", dial: "+231", currency: "LRD" },
  { name: "Libya", iso2: "LY", dial: "+218", currency: "LYD" },
  { name: "Liechtenstein", iso2: "LI", dial: "+423", currency: "CHF" },
  { name: "Lithuania", iso2: "LT", dial: "+370", currency: "EUR" },
  { name: "Luxembourg", iso2: "LU", dial: "+352", currency: "EUR" },
  { name: "Macau", iso2: "MO", dial: "+853", currency: "MOP" },
  { name: "Madagascar", iso2: "MG", dial: "+261", currency: "MGA" },
  { name: "Malawi", iso2: "MW", dial: "+265", currency: "MWK" },
  { name: "Malaysia", iso2: "MY", dial: "+60", currency: "MYR" },
  { name: "Maldives", iso2: "MV", dial: "+960", currency: "MVR" },
  { name: "Mali", iso2: "ML", dial: "+223", currency: "XOF" },
  { name: "Malta", iso2: "MT", dial: "+356", currency: "EUR" },
  { name: "Marshall Islands", iso2: "MH", dial: "+692", currency: "USD" },
  { name: "Mauritania", iso2: "MR", dial: "+222", currency: "MRU" },
  { name: "Mauritius", iso2: "MU", dial: "+230", currency: "MUR" },
  { name: "Mexico", iso2: "MX", dial: "+52", currency: "MXN" },
  { name: "Micronesia", iso2: "FM", dial: "+691", currency: "USD" },
  { name: "Moldova", iso2: "MD", dial: "+373", currency: "MDL" },
  { name: "Monaco", iso2: "MC", dial: "+377", currency: "EUR" },
  { name: "Mongolia", iso2: "MN", dial: "+976", currency: "MNT" },
  { name: "Montenegro", iso2: "ME", dial: "+382", currency: "EUR" },
  { name: "Montserrat", iso2: "MS", dial: "+1664", currency: "XCD" },
  { name: "Morocco", iso2: "MA", dial: "+212", currency: "MAD" },
  { name: "Mozambique", iso2: "MZ", dial: "+258", currency: "MZN" },
  { name: "Myanmar", iso2: "MM", dial: "+95", currency: "MMK" },
  { name: "Namibia", iso2: "NA", dial: "+264", currency: "NAD" },
  { name: "Nauru", iso2: "NR", dial: "+674", currency: "AUD" },
  { name: "Nepal", iso2: "NP", dial: "+977", currency: "NPR" },
  { name: "Netherlands", iso2: "NL", dial: "+31", currency: "EUR" },
  { name: "New Caledonia", iso2: "NC", dial: "+687", currency: "XPF" },
  { name: "New Zealand", iso2: "NZ", dial: "+64", currency: "NZD" },
  { name: "Nicaragua", iso2: "NI", dial: "+505", currency: "NIO" },
  { name: "Niger", iso2: "NE", dial: "+227", currency: "XOF" },
  { name: "Nigeria", iso2: "NG", dial: "+234", currency: "NGN" },
  { name: "Niue", iso2: "NU", dial: "+683", currency: "NZD" },
  { name: "North Korea", iso2: "KP", dial: "+850", currency: "KPW" },
  { name: "North Macedonia", iso2: "MK", dial: "+389", currency: "MKD" },
  { name: "Northern Mariana Islands", iso2: "MP", dial: "+1670", currency: "USD" },
  { name: "Norway", iso2: "NO", dial: "+47", currency: "NOK" },
  { name: "Oman", iso2: "OM", dial: "+968", currency: "OMR" },
  { name: "Pakistan", iso2: "PK", dial: "+92", currency: "PKR" },
  { name: "Palau", iso2: "PW", dial: "+680", currency: "USD" },
  { name: "Palestine", iso2: "PS", dial: "+970", currency: "ILS" },
  { name: "Panama", iso2: "PA", dial: "+507", currency: "PAB" },
  { name: "Papua New Guinea", iso2: "PG", dial: "+675", currency: "PGK" },
  { name: "Paraguay", iso2: "PY", dial: "+595", currency: "PYG" },
  { name: "Peru", iso2: "PE", dial: "+51", currency: "PEN" },
  { name: "Philippines", iso2: "PH", dial: "+63", currency: "PHP" },
  { name: "Poland", iso2: "PL", dial: "+48", currency: "PLN" },
  { name: "Portugal", iso2: "PT", dial: "+351", currency: "EUR" },
  { name: "Puerto Rico", iso2: "PR", dial: "+1787", currency: "USD" },
  { name: "Qatar", iso2: "QA", dial: "+974", currency: "QAR" },
  { name: "Réunion", iso2: "RE", dial: "+262", currency: "EUR" },
  { name: "Romania", iso2: "RO", dial: "+40", currency: "RON" },
  { name: "Russia", iso2: "RU", dial: "+7", currency: "RUB" },
  { name: "Rwanda", iso2: "RW", dial: "+250", currency: "RWF" },
  { name: "Saint Kitts and Nevis", iso2: "KN", dial: "+1869", currency: "XCD" },
  { name: "Saint Lucia", iso2: "LC", dial: "+1758", currency: "XCD" },
  { name: "Saint Vincent and the Grenadines", iso2: "VC", dial: "+1784", currency: "XCD" },
  { name: "Samoa", iso2: "WS", dial: "+685", currency: "WST" },
  { name: "San Marino", iso2: "SM", dial: "+378", currency: "EUR" },
  { name: "Sao Tome and Principe", iso2: "ST", dial: "+239", currency: "STN" },
  { name: "Saudi Arabia", iso2: "SA", dial: "+966", currency: "SAR" },
  { name: "Senegal", iso2: "SN", dial: "+221", currency: "XOF" },
  { name: "Serbia", iso2: "RS", dial: "+381", currency: "RSD" },
  { name: "Seychelles", iso2: "SC", dial: "+248", currency: "SCR" },
  { name: "Sierra Leone", iso2: "SL", dial: "+232", currency: "SLE" },
  { name: "Singapore", iso2: "SG", dial: "+65", currency: "SGD" },
  { name: "Sint Maarten", iso2: "SX", dial: "+1721", currency: "ANG" },
  { name: "Slovakia", iso2: "SK", dial: "+421", currency: "EUR" },
  { name: "Slovenia", iso2: "SI", dial: "+386", currency: "EUR" },
  { name: "Solomon Islands", iso2: "SB", dial: "+677", currency: "SBD" },
  { name: "Somalia", iso2: "SO", dial: "+252", currency: "SOS" },
  { name: "South Africa", iso2: "ZA", dial: "+27", currency: "ZAR" },
  { name: "South Korea", iso2: "KR", dial: "+82", currency: "KRW" },
  { name: "South Sudan", iso2: "SS", dial: "+211", currency: "SSP" },
  { name: "Spain", iso2: "ES", dial: "+34", currency: "EUR" },
  { name: "Sri Lanka", iso2: "LK", dial: "+94", currency: "LKR" },
  { name: "Sudan", iso2: "SD", dial: "+249", currency: "SDG" },
  { name: "Suriname", iso2: "SR", dial: "+597", currency: "SRD" },
  { name: "Sweden", iso2: "SE", dial: "+46", currency: "SEK" },
  { name: "Switzerland", iso2: "CH", dial: "+41", currency: "CHF" },
  { name: "Syria", iso2: "SY", dial: "+963", currency: "SYP" },
  { name: "Taiwan", iso2: "TW", dial: "+886", currency: "TWD" },
  { name: "Tajikistan", iso2: "TJ", dial: "+992", currency: "TJS" },
  { name: "Tanzania", iso2: "TZ", dial: "+255", currency: "TZS" },
  { name: "Thailand", iso2: "TH", dial: "+66", currency: "THB" },
  { name: "Timor-Leste", iso2: "TL", dial: "+670", currency: "USD" },
  { name: "Togo", iso2: "TG", dial: "+228", currency: "XOF" },
  { name: "Tokelau", iso2: "TK", dial: "+690", currency: "NZD" },
  { name: "Tonga", iso2: "TO", dial: "+676", currency: "TOP" },
  { name: "Trinidad and Tobago", iso2: "TT", dial: "+1868", currency: "TTD" },
  { name: "Tunisia", iso2: "TN", dial: "+216", currency: "TND" },
  { name: "Turkey", iso2: "TR", dial: "+90", currency: "TRY" },
  { name: "Turkmenistan", iso2: "TM", dial: "+993", currency: "TMT" },
  { name: "Turks and Caicos Islands", iso2: "TC", dial: "+1649", currency: "USD" },
  { name: "Tuvalu", iso2: "TV", dial: "+688", currency: "AUD" },
  { name: "U.S. Virgin Islands", iso2: "VI", dial: "+1340", currency: "USD" },
  { name: "Uganda", iso2: "UG", dial: "+256", currency: "UGX" },
  { name: "Ukraine", iso2: "UA", dial: "+380", currency: "UAH" },
  { name: "United Arab Emirates", iso2: "AE", dial: "+971", currency: "AED" },
  { name: "United Kingdom", iso2: "GB", dial: "+44", currency: "GBP" },
  { name: "United States", iso2: "US", dial: "+1", currency: "USD" },
  { name: "Uruguay", iso2: "UY", dial: "+598", currency: "UYU" },
  { name: "Uzbekistan", iso2: "UZ", dial: "+998", currency: "UZS" },
  { name: "Vanuatu", iso2: "VU", dial: "+678", currency: "VUV" },
  { name: "Vatican City", iso2: "VA", dial: "+379", currency: "EUR" },
  { name: "Venezuela", iso2: "VE", dial: "+58", currency: "VES" },
  { name: "Vietnam", iso2: "VN", dial: "+84", currency: "VND" },
  { name: "Wallis and Futuna", iso2: "WF", dial: "+681", currency: "XPF" },
  { name: "Yemen", iso2: "YE", dial: "+967", currency: "YER" },
  { name: "Zambia", iso2: "ZM", dial: "+260", currency: "ZMW" },
  { name: "Zimbabwe", iso2: "ZW", dial: "+263", currency: "ZWL" },
];

/** Hapus diakritik + lowercase utk pencocokan nama longgar ("cote d'ivoire" === "Côte d'Ivoire"). */
function foldName(s: string): string {
  return s.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().trim();
}

/**
 * Cari negara by nama (case-insensitive, toleran diakritik) ATAU kode dial
 * (boleh dengan/tanpa "+"). Return undefined bila tidak ketemu.
 */
export function findCountry(nameOrDial: string): Country | undefined {
  const q = (nameOrDial ?? "").trim();
  if (!q) return undefined;
  const qFold = foldName(q);
  const byName = COUNTRIES.find((c) => foldName(c.name) === qFold);
  if (byName) return byName;
  const qDial = q.startsWith("+") ? q : `+${q.replace(/^\+/, "")}`;
  return COUNTRIES.find((c) => c.dial === qDial);
}
